### ISSUE TITLE
Paper Server mods.yml Issue

### ISSUE THREAD

**Issue by jaydenhagerty** [LunarClient/Apollo#60]
Hi! I'm starting an SMP server and I'm hoping to disable the "minimap" mod. It's a Paper server, so I downloaded the Bukkit jar file for Apollo and added it. No matter what I do, the changes I make in the mods.yml file have no effect on the server. In most cases, when I restart the server to try and add those changes, it clears everything I've written and sets it back to default (despite me saving my work).

All I want to do is disable the minimap mod when people join my server on Lunar Client, but nothing has worked. Not sure if this is a bug or my own user error, but I've read the documentation and I'm relatively confident that I didn't screw anything up.

I'd love some advice on what else to try, and thank you for your time!

**Comment by vectrixdevelops** [comment]
Hey! Have you tried modifying the configuration file while the server is stopped, then starting it?

**Comment by MathsAnalysis** [comment]
In fact by any chance is there a way to not have them enabled in general?

**Comment by jaydenhagerty** [comment]
I'm not sure what you mean.

**Comment by KneesDev** [comment]
I am experiencing the same issue

**Comment by TrentinTheKid** [comment]
We've pushed an update to resolve this issue, can you test this once again on the latest version of Apollo?

@jaydenhagerty @KneesDev @MathsAnalysis

**Comment by KneesDev** [comment]
Could you provide me with a download link, @TrentinTheKid? Thanks!

**Comment by TrentinTheKid** [comment]
> Could you provide me with a download link, @TrentinTheKid? Thanks!

https://lunarclient.dev/apollo/downloads

**Comment by KneesDev** [comment]
Has an update been pushed for Bungee too? My server uses Bungee and experiences the same issue.

**Comment by TrentinTheKid** [comment]
> Has an update been pushed for Bungee too? My server uses Bungee and experiences the same issue.

It was a client-sided update, nothing changed inside of Apollo. It's just recommended to always use the latest release. That being said, yes it should work for bungee.

**Comment by KneesDev** [comment]
I see. I just tried and it doesn't seem to be working. Should I send my config or something?

**Comment by TrentinTheKid** [comment]
> I see. I just tried and it doesn't seem to be working. Should I send my config or something?

Make sure your server is offline when you change the config, then start it after saving the file. If you've followed that process, please send your config file.

**Comment by KneesDev** [comment]
Got it. Here are the files used for configuration:
**config.yml**
```yaml
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
# General and module specific settings. https://lunarclient.dev/apollo/server-owners/config
mcstats:
    # Set to 'true' to send statistics to MCStats, otherwise 'false'.
    send-stats: false
    # Your server's installation id used for stats.
    installation-id: ae57f843-d6d6-4f6f-8a0a-bb390918a122
    # Set to 'true' to send your minecraft server statistics to MCStats, otherwise 'false'.
    server-statistics: false
    # Set to 'true' to send your server hardware information to MCStats, otherwise 'false'.
    hardware-information: false
    # Set to 'true' to send your server software information to MCStats, otherwise 'false'.
    software-information: false
    # Set to 'true' to send your server cpu and ram usage to MCStats, otherwise 'false'.
    performance: false
    # Set to 'true' to send your server player count to MCStats, otherwise 'false'.
    counts: false
# Set to 'true' to send opped players available update message, otherwise 'false'.
send-updater-message: false
modules:
    beam:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    border:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    chat:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    colored_fire:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    cooldown:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    entity:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    hologram:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    limb:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    nametag:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    notification:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    server_rule:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
        # Set to 'true' to enable leaving game warning, otherwise 'false'.
        competitive-game: false
        # A list of commands that will trigger the competitive popup.
        competitive-commands:
        - /server
        - /servers
        - /hub
        # Set to 'true' to disable shaders, otherwise 'false'.
        disable-shaders: false
        # Set to 'true' to disable chunk reloading, otherwise 'false'.
        disable-chunk-reloading: false
        # Set to 'true' to disable broadcasting, otherwise 'false'.
        disable-broadcasting: false
        # Set to 'true' to enable anti portal traps, otherwise 'false'.
        anti-portal-traps: true
        # Set to 'true' to override brightness, otherwise 'false'.
        override-brightness: false
        # Set the brightness amount.
        brightness: 50
        # Set to 'true' to override nametag render distance, otherwise 'false'.
        override-nametag-render-distance: false
        # Set the nametag render distance amount.
        nametag-render-distance: 64
        # Set to 'true' to override max chat length, otherwise 'false'.
        override-max-chat-length: false
        # Set the nametag render distance amount.
        max-chat-length: 256
    staff_mod:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    stopwatch:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    team:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    title:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    transfer:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    vignette:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: true
    waypoint:
        # Set to 'true' to enable this module, otherwise set 'false'.
        enable: false
        # Sets the default waypoints to send to the player.
        default-waypoints:
        -   name: Spawn
            location:
                world: world
                x: 0
                y: 100
                z: 0
            color: '#FF0000'
            prevent-removal: false
            hidden: false
        # Set to 'true' to let servers handle waypoints, otherwise 'false'.
        server-handles-waypoints: false
```
**mods.yml**
```yaml
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
# Lunar Client mod option overrides. https://lunarclient.dev/apollo/server-owners/config
mod_setting:
    # Set to 'true' to enable this module, otherwise set 'false'.
    enable: true
    replaymod:
        enabled:
        indicator:
        auto-post-process:
        show-server-ip:
        auto-sync:
        timeline-length:
        ask-for-open-eye:
        skip-post-render-gui:
        skip-post-screenshot-gui:
        path-preview:
        lunar-u-i:
        notifications:
        record-singleplayer:
        record-server:
        auto-start-recording:
        rename-dialog:
        show-chat:
    one-seven-visuals:
        enabled:
    fps:
        enabled:
        scale:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    cps:
        enabled:
        scale:
        right-click:
        show-c-p-s-text:
        line-color:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    sba:
        enabled:
        hide-health-bar:
        hide-food-bar:
        hide-pet-health-bar:
        skeleton-helmet-bars:
        cooldown-prediction:
        leg-monkey-lvl100:
        compact-tab-list:
        show-item-cooldowns:
        use-lunar-cooldowns:
        hide-true-defense:
        special-zealot-alert:
        zealot-counter-explosive-bow-support:
        zealot-color-boolean:
        zealot-color:
        lock-slots:
        stop-dropping-selling-rare-items:
        avoid-blinking-night-vision:
        make-backpack-inventories-colored:
        fishing-sound-indicator:
        change-bar-color-for-potions:
        color-ender-chest-in-end:
        end-ender-chest-color:
        outbid-alert-sound:
        outbid-alert-sound-in-other-games:
        hide-other-player-presents:
        # Requires Fast Render to be OFF.
        entity-glow:
        dropped-items-glow:
        dropped-items-glow-on-island:
        hide-sven-pup-nametags:
        hide-players-in-lobby:
        hide-spawn-point-players:
        hide-bones:
        bigger-fishing-wake:
        stop-rat-sounds:
        stop-only-rat-squeak:
        fishing-particle-overlay:
        fishing-particle-overlay-color:
        dungeon-teammates-glow:
        critical-health-dungeon-teammate-warning:
        show-dungeon-teammate-name-overlay:
        show-healing-circle-wall:
        healing-circle-opacity:
        stop-bonzo-staff-sounds:
        show-salvage-essences-counter:
        reset-salvaged-essences-after-leaving-menu:
        change-dungeon-map-zoom-with-keyboard:
        hide-enchant-description:
        enable-message-when-breaking-park:
        show-backpack-preview:
        show-backpack-holding-shift:
        backpack-preview-ah:
        cake-bag-preview:
        backpack-opening-sound:
        fancy-warp-menu:
        warp-advanced-mode:
        disable-enderman-teleportion-effect:
        hide-grey-enchants:
        show-item-anvil-uses:
        replace-roman-numerals-with-numbers:
        dont-replace-roman-numerals-in-item-name:
        show-enchantments-reforges:
        show-broken-fragments:
        show-base-stat-boost-percentage:
        base-stat-boost-color-by-rarity:
        show-item-dungeon-floor:
        show-rarity-upgraded:
        show-stacking-enchant-progress:
        # Shows the kills for swords that give stats reflecting the enemies killed with said sword (ex. Fels Sword)
        show-sword-kills:
        enchantment-lore-parsing:
        highlight-special-enchantments:
        show-experimentation-table-tooltips:
        developer-mode:
        show-sky-block-item-i-d:
        dont-reset-cursor-inventory:
        show-personal-compactor-preview:
        reforge-filter:
        show-ender-chest-preview:
        disable-empty-glass-panes:
        disable-teleport-pad-messages:
        disable-magical-soup-messages:
        disable-mort-messages:
        disable-boss-messages:
        disable-spirit-sceptre-messages:
        player-symbols-in-chat:
        show-profile-type:
        show-nether-faction:
        trevor-the-trapper-features:
        trevor-highlight-tracked-entity:
        trevor-show-quest-cooldown:
    toggle-sneak:
        enabled:
        toggle-sprint:
        toggle-sneak:
        double-tap:
        toggle-sneak-container:
        fly-boost:
        fly-boost-amount:
    zoom:
        enabled:
        # Quickly pressing and releasing the key will toggle zoom
        toggle-key-zoom:
        # When zoomed in the camera movement will move smoothly (cinematic camera)
        smooth-camera:
        # Add a transition when zooming in and out.
        smooth-zoom:
        # Adjust the zoom depth using Mouse Scroll Wheel
        variable-zoom:
        # Change the initial zoom depth.
        zoom-divisor:
    hypixel-mod:
        enabled:
        remove-guild-on-tab:
        remove-guild-motd:
        short-channel-names:
        auto-friend:
        auto-tip:
        auto-g-g:
        anti-g-g:
        auto-who:
        level-head:
        hypixel-autocomplete:
        level-color:
        level-head-number-color:
        level-above:
        hide-private-messages:
        hide-team-chat:
        hide-party-chat:
        hide-guild-chat:
        hide-shout:
        hide-spectator-chat:
        remove-lobby-statuses:
        hide-join-messages:
        hide-leave-messages:
        hide-soul-well-announcements:
    hypixel-bedwars:
        enabled:
        # Recolor the beds in-game according to the team's color
        colored-beds:
        # Replaces normal hearts with hardcore hearts once your bed is lost
        bw-hardcore-hearts:
    quickplay:
        enabled:
    armorstatus:
        enabled:
        scale:
        move-armor-individually:
        item-name:
        item-count:
        show-while-typing:
        text-shadow:
        damage-overlay:
        item-damage:
        armor-damage:
        max-damage:
        static-damage-colors:
        name-text-color:
        highest-color:
        high-color:
        medium-color:
        medium-low-color:
        low-color:
        lowest-color:
    keystrokes:
        enabled:
        scale:
        key-strokes-clicks:
        left-c-p-s:
        right-c-p-s:
        key-strokes-movement:
        key-strokes-spacebar:
        use-arrows:
        text-shadow:
        border:
        inner-border:
        border-thickness:
        box-size:
        border-color:
        text-color:
        text-pressed-color:
        background-color:
        background-pressed-color:
        key-fade-delay:
    coordinates:
        enabled:
        scale:
        background:
        text-shadow:
        show-while-typing:
        border:
        border-thickness:
        move-children-individually:
        background-color:
        border-color:
    day-counter:
        enabled:
        scale:
        use-world-type:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    crosshair:
        enabled:
        crosshair-thickness:
        crosshair-size:
        crosshair-gap:
        crosshair-dot:
        crosshair-outline:
        outline-thickness:
        outline-color:
        custom-scale:
        color:
        friendly-color:
        enemy-color:
    potion-effects:
        enabled:
        scale:
        show-in-inventory:
        show-while-typing:
        effect-name:
        text-shadow:
        hide-modern-icons:
        potion-blink:
        blink-duration:
        color-name-based-on-effect:
        text-color:
        duration-color:
        exclude-perm:
        exclude-speed:
        exclude-slowness:
        exclude-strength:
        exclude-jump-boost:
        exclude-regen:
        exclude-fire-res:
        exclude-water-breathing:
        exclude-night-vision:
        exclude-weakness:
        exclude-poison:
        exclude-haste:
        exclude-invis:
    direction-hud:
        enabled:
        scale:
        width:
        text-shadow:
        # Show the cardinal directions in BOLD.
        bold-directions:
        background:
        border:
        border-thickness:
        use-legacy-style:
        show-marker:
        show-marker-value:
        background-color:
        border-color:
        marker-color:
        direction-color:
    titles:
        enabled:
        scale:
        show-in-hud-editor:
        title-color:
        subtitle-color:
    waypoints:
        enabled: false
        death-waypoint:
        # Adds a waypoint if coordinates are clicked in chat.
        add-from-chat:
        waypoint-beams:
        box-border:
        text-shadow:
        box-padding:
        # Only show each waypoint when looking near then in the world
        only-show-when-looking-near:
        # Show simpler text icons above each waypoint
        show-icons:
        label-scale:
        icon-scale:
    hit-color:
        enabled:
        hit-armor-color:
        should-color-armor:
    scoreboard:
        enabled:
        scale:
        numbers:
        text-shadow:
        border-thickness:
        border:
        background-color:
        border-color:
    item-counter:
        enabled:
        scale:
    ping:
        enabled:
        scale:
        # Faster updates may impact performance
        update-interval-sec:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    motion-blur:
        enabled:
        old-blur:
        value:
    pack-organizer:
        enabled:
        show-incompatible:
    chat:
        enabled:
        # Choose whether or not you want to increase the message history in chat
        unlimited-chat:
        # Choose whether or not you want to stack multiple of the same messages in chat
        stack-messages:
        # Moves the chat up 12 pixels so it doesn't block health bar
        chat-height:
        chat-background-opacity:
        # Show text shadow on chat lines
        chat-shadow:
        disable-chat:
        no-close-my-chat:
        # ENABLED: Completely hides filtered messages DISABLED: Replaces filtered words with asterisks
        stop-profane-messages:
        input-field-opacity:
        chat-ping-sound:
        smooth-chat:
        smooth-chat-speed:
        chat-timestamps:
        # Makes the timestamp italics
        timestamp-italics:
        # Makes the timestamp bold
        timestamp-bold:
        # Use a 12-hour clock, or a 24-hour clock if disabled
        twelve-hour-clock:
        show-am-pm:
        show-seconds:
        # Adds square brackets around the timestamp
        show-brackets:
        # Copies the hovered chat message when holding the keybind and clicking.
        copy-chat:
    tab:
        enabled:
        # Quickly pressing and releasing the key will toggle tab
        toggle-key-tab:
        header-color:
        footer-color:
        background-color:
        ping-row:
        rows-color:
        disable-header:
        display-player-head:
        disable-footer:
        # Hide Hypixel NPC on tab
        hide-n-p-c:
        show-lunar-icons-on-right:
        # An option to toggle LC logos in player list tab overlay.
        tab-logo:
        highlight-own-name:
        name-color:
        name-shadow:
        hide-ping:
        hide-ping-if-over500:
        display-ping-as-number:
        dynamic-ping-color:
        ping-number-shadow:
        ping-number-color:
        low-ping-number-color:
        medium-ping-number-color:
        high-ping-number-color:
        extreme-ping-number-color:
    nametag:
        enabled:
        nametag-shadow:
        # An option to see your own nametag in third person
        nametag:
        # An option to toggle LC logos in nametags
        nametag-logo:
        # Determines if we should send the message when nametags are toggled.
        toggle-nametags:
        nametag-background-opacity:
    scrollable-tooltips:
        enabled:
        start-at-top:
        vertical-keybind:
        text-shadow:
        wrap-text:
    uhc-overlay:
        enabled:
        gold-ingot-scale:
        gold-nugget-scale:
        gold-ore-scale:
        gold-apple-scale:
        skull-scale:
    particle-changer:
        enabled:
        always-enchant-strikes:
        affect-enchanted-weapons:
        # Hide your players potion effect particles when you're in first person
        hide-first-person-particles:
        color:
        scale:
        particle-multiplier:
        hide-particle:
        overlay-color:
    nick-hider:
        enabled:
        hide-name:
        hide-real-name:
        hide-others-names:
        hide-own-skin:
        use-real-skin:
        hide-others-skin:
    cooldowns:
        enabled:
        scale:
    worldedit-cui:
        enabled:
        position-one-color:
        position-two-color:
        outline-color:
    clock:
        enabled:
        scale:
        military-time:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    stopwatch:
        enabled:
        scale:
        reset-every-start:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    playtime:
        enabled:
        scale:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    memory:
        enabled:
        scale:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    combo:
        enabled:
        scale:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    reach-display:
        enabled:
        scale:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    time-changer:
        enabled:
        time-changer-time:
        horizon-y-level:
        use-real-time:
    server-address:
        enabled:
        scale:
        server-icon:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    saturation:
        enabled:
        show-saturation-overlay:
        show-appleskin-tooltip:
        show-held-item-hunger:
        show-held-item-saturation:
    color-saturation:
        enabled:
        color-saturation-hue:
        color-saturation-saturation:
        color-saturation-brightness:
        color-saturation-contrast:
    item-physics:
        enabled:
        rotation-speed:
    tnt-countdown:
        enabled:
        # Offset the default tnt delay in ticks. 1 second is 20 ticks
        adjust-fuse-time:
        background:
        text-shadow:
        # Should the color stay the same the entire time.
        static-countdown-color:
        color:
        prefix-color:
    item-tracker:
        enabled:
        scale:
        text-shadow:
        skyblock-only:
        # How long the text should stay on screen (seconds)
        popup-duration-sec:
    shiny-pots:
        enabled:
        colored-potions:
        render-glint-behind-potion:
        render-entire-slot:
    3d-skins:
        enabled:
        render-distance-lod:
        enable-hat:
        enable-jacket:
        enable-left-sleeve:
        enable-right-sleeve:
        enable-left-pants:
        enable-right-pants:
        base-voxel-size:
        body-voxel-width-size:
        head-voxel-size:
        enable-skulls:
        enable-skulls-items:
        skull-voxel-size:
    glint-colorizer:
        enabled:
        # Use a custom blending algorithm which supports darker colours
        use-lunar-equation:
        # Recolor the glints of items
        override-item-glint:
        item-glint-lunar-color:
        item-glint-vanilla-color:
        # Recolor the glints of worn armor
        override-armor-glint:
        armor-glint-lunar:
        armor-glint-vanilla:
    momentum:
        enabled:
        scale:
        # If enabled then Y velocity is not used in the final speed.
        use-ground-speed:
        # If this is disabled then instant velocity is used
        use-average-velocity:
        # Determines how many times a second velocity is calculated. Lower values will show a smoother velocity
        averaging-period:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    block-outline:
        enabled:
        block-outline-color:
        block-overlay-color:
        block-outline-width:
        block-overlay:
        block-outline:
    screenshot:
        enabled:
        copy-automatically:
        upload-option:
        tweet-option:
        copy-option:
    fov:
        enabled:
        # Determines if your FOV changes as you move.
        static-f-o-v:
        default-fov:
        aiming-modifier:
        aiming-min:
        aiming-max:
        speed-f-o-v:
        speed-two-f-o-v:
        slowness-f-o-v:
        movement-modifier:
        movement-min:
        movement-max:
        sprinting-f-o-v:
        sprint-modifier:
        sprint-min:
        sprint-max:
        flying-fov:
        flying-modifier:
        flying-min:
        flying-max:
    fog:
        enabled:
        water-fog-density:
        render-distance-fog-density:
        render-distance-fog-color-toggle:
        render-distance-fog-color:
    auto-text-hotkey:
        enabled:
    mumble-link:
        enabled:
    2d-items:
        enabled:
    bossbar:
        enabled:
        scale:
        render-bar:
        custom-boss-bar:
        bar-color:
    freelook:
        enabled: false
        invert-pitch:
        invert-yaw:
        # Quickly pressing and releasing the key will toggle freelook
        toggle-key-freelook:
        # When zoomed in the camera movement will move smoothly (cinematic camera)
        smooth-camera:
    pvp-info:
        enabled:
        reset-on-world-change:
    snaplook:
        enabled: false
        # When zoomed in the camera movement will move smoothly (cinematic camera)
        smooth-camera:
    team-view:
        enabled:
    pack-display:
        enabled:
        scale:
        pack-icon:
        pack-description:
        text-shadow:
        background:
        # If this is disabled the background will change size with the text.
        static-background-width:
        background-width:
        background-height:
        brackets:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
    menu-blur:
        enabled:
        blur-strength:
        blur-lunar-toggle:
        blur-lunar-background:
        blur-inventory-toggle:
        blur-inventory-background:
        blur-pause-toggle:
        blur-pause-background:
    minimap:
        enabled: false
        scale:
        map-width:
        map-height:
        map-zoom:
        rotate-with-player:
        border:
        border-color:
        border-thickness:
        compass:
        compass-color:
        compass-shadow:
        player-marker-color:
        player-marker-size:
        entity-marker-opacity:
        entity-marker-size:
        entity-marker-shadow:
        show-coordinates:
    hitbox:
        enabled: false
        hitbox-player-line-width:
        hitbox-player-line-color:
        hitbox-player-look-vector:
        hitbox-player-show:
        hitbox-item-line-width:
        hitbox-item-line-color:
        hitbox-item-look-vector:
        hitbox-item-show:
        hitbox-projectile-line-width:
        hitbox-projectile-line-color:
        hitbox-projectile-look-vector:
        hitbox-projectile-show:
        hitbox-mob-line-width:
        hitbox-mob-line-color:
        hitbox-mob-look-vector:
        hitbox-mob-show:
        hitbox-exp-orb-line-width:
        hitbox-exp-orb-line-color:
        hitbox-exp-orb-look-vector:
        hitbox-exp-orb-show:
    lighting:
        enabled:
        full-bright:
        brightness-boost:
    weather-changer:
        enabled:
        rain-strength:
        # Augment the rain/snow color
        rain-color:
    chunk-borders:
        enabled:
        grid-color:
        inner-chunk-corner-color:
        outer-chunk-corner-color:
    sound-changer:
        enabled:
    waila:
        enabled:
        scale:
        show-entities:
        text-shadow:
        background:
        border:
        border-thickness:
        text-color:
        background-color:
        border-color:
        vertical-spacing:
        horizontal-spacing:
    neu:
        enabled:
    hurt-cam:
        enabled:
        disable-hurt-cam:
        hurt-shaking-intensity:
        old-camera-tilt:
    damage-tint:
        enabled:
        vignette-color:
        # Intensity of the tint.
        vignette-intensity:
        # Show the tint when you have less than this amount of health as a percentage.
        show-vignette-below:
        # Plays a heartbeat, becoming faster the lower your health.
        heartbeat-audio:
```
